### ISSUE TITLE
获取A&D血压计中的血压获取不到

### ISSUE THREAD

**Issue by zhujinhu21** [WD3/BluetoothHDP#1]
我用你的例子测试链接A&D的血压计，可以获取到心率，但是获取不到血压。
public void getBloodMeasure(MeasureEvent event) {
((AndroidBloodMeasure) event.getMeasures()).getHPressure()
获取到的血压为0
}

**Comment by zhujinhu21** [comment]
具体的错误信息，得出的测量日期为null。
03-06 11:17:13.010: W/System.err(10524): java.lang.NullPointerException
03-06 11:17:13.010: W/System.err(10524):    at Config.DateDecoder.setCentury(DateDecoder.java:7)
03-06 11:17:13.010: W/System.err(10524):    at Config.BloodPressureAgent.generateMeasure(BloodPressureAgent.java:174)
03-06 11:17:13.010: W/System.err(10524):    at Config.BloodPressureAgent.addMeasure(BloodPressureAgent.java:67)
03-06 11:17:13.010: W/System.err(10524):    at com.example.bluetooth.health.BluetoothHDPService$2$1.getBloodMeasure(BluetoothHDPService.java:331)
03-06 11:17:13.010: W/System.err(10524):    at com.pku.wireless.AndroidMeasureDecoder.receiveMeasures(AndroidMeasureDecoder.java:79)
03-06 11:17:13.010: W/System.err(10524):    at com.pku.wireless.AndroidEventManager.receivedMeasure(AndroidEventManager.java:44)
03-06 11:17:13.010: W/System.err(10524):    at es.libresoft.openhealth.events.InternalEventReporter.receivedMeasure(InternalEventReporter.java:56)
03-06 11:17:13.010: W/System.err(10524):    at ieee_11073.part_20601.phd.dim.manager.MDSManager.MDS_Dynamic_Data_Update_Fixed(MDSManager.java:273)
03-06 11:17:13.010: W/System.err(10524):    at ieee_11073.part_20601.fsm.manager.MOperating.mdc_noti_scan_report_fixed(MOperating.java:488)
03-06 11:17:13.010: W/System.err(10524):    at ieee_11073.part_20601.fsm.manager.MOperating.process_MDS_Object_Event(MOperating.java:470)
03-06 11:17:13.010: W/System.err(10524):    at ieee_11073.part_20601.fsm.manager.MOperating.process_event_report(MOperating.java:427)
03-06 11:17:13.010: W/System.err(10524):    at ieee_11073.part_20601.fsm.manager.MOperating.roiv_cmip_confirmed_event_report(MOperating.java:414)
03-06 11:17:13.010: W/System.err(10524):    at ieee_11073.part_20601.fsm.manager.MOperating.processDataApdu(MOperating.java:281)
03-06 11:17:13.010: W/System.err(10524):    at ieee_11073.part_20601.fsm.manager.MOperating.process_20601_PrstApdu(MOperating.java:260)
03-06 11:17:13.010: W/System.err(10524):    at ieee_11073.part_20601.fsm.manager.MOperating.access$0(MOperating.java:254)
03-06 11:17:13.010: W/System.err(10524):    at ieee_11073.part_20601.fsm.manager.MOperating$1.processPrstApdu(MOperating.java:120)
03-06 11:17:13.010: W/System.err(10524):    at ieee_11073.part_20601.fsm.manager.MOperating.process(MOperating.java:132)
03-06 11:17:13.010: W/System.err(10524):    at ieee_11073.part_20601.fsm.manager.ManagerStateController$DispatcherApduThread.run(ManagerStateController.java:223)
